- name: Enable Intranet Services
  hosts: all
  become: yes
  tasks:
    - name: Install httpd and firewalld
      apt:
        name:
          - nginx
        state: latest
    - name: Test html page is installed
      copy:
        content: "Welcome to the intranet!\n"
        dest: /var/www/html/index.html
- name: Test intranet web server ## test ket noi den web
  hosts: localhost
  become: no
  tasks:
    - name: connect to intranet webserver
      uri:
        url: http://172.10.20.50
        status_code: 200
